import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex h-screen flex-col items-center justify-center",
          "bg-gradient-to-br from-white to-gray-300",
          "dark:bg-gradient-to-br dark:from-slate-900 dark:to-slate-800"
        )}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
